#!/bin/sh
#
# ${project trunk_name} - ${project trunk_description}
# Copyright (C) ${date %Y} ${user name}
# Written by ${user email}
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

TEST_SUBJECT="fill me in"
. test_prelude

cat > test.in << 'fubar'
Hello, World!
fubar
test $$? -eq 0 || no_result

cat > test.ok << 'fubar'
Hello, World!
fubar
test $$? -eq 0 || no_result

command-to-be-tested -? < test.in > test.out
test $$? -eq 0 || fail

diff test.ok test.out
test $$? -eq 0 || fail

#
# Only definite negatives are possible.
# The functionality exercised by this test appears to work,
# no other guarantees are made.
#
pass

# vim: set ts=8 sw=4 et :
