.\"
.\" libexplain - Explain errno values returned by libc functions
.\" Copyright (C) 2012 Peter Miller
.\"
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 3 of the License, or (at your
.\" option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License along
.\" with this program. If not, see <http://www.gnu.org/licenses/>.
.\"
.ds n) explain_lchmod_or_die
.TH explain_lchmod_or_die 3
.SH NAME
explain_lchmod_or_die \- change permissions of a file and report errors
.if require_index \{
.XX "explain_lchmod_or_die(3)" \
    "change permissions of a file and report errors"
.\}
.SH SYNOPSIS
#include <libexplain/lchmod.h>
.sp 0.3
void explain_lchmod_or_die(const char *pathname, mode_t mode);
.br
int explain_lchmod_on_error(const char *pathname, mode_t mode);
.SH DESCRIPTION
The \f[B]explain_lchmod_or_die\fP function is used to call the
\f[I]lchmod\fP(2) system call. On failure an explanation will be printed to
\f[I]stderr\fP, obtained from the \f[I]explain_lchmod\fP(3) function, and
then the process terminates by calling \f[CW]exit(EXIT_FAILURE)\fP.
.PP
The \f[B]explain_lchmod_on_error\fP function is used to call the
\f[I]lchmod\fP(2) system call. On failure an explanation will be printed to
\f[I]stderr\fP, obtained from the \f[I]explain_lchmod\fP(3) function, but
still returns to the caller.
.TP 8n
\f[I]pathname\fP
The pathname, exactly as to be passed to the \f[I]lchmod\fP(2) system call.
.TP 8n
\f[I]mode\fP
The mode, exactly as to be passed to the \f[I]lchmod\fP(2) system call.
.\" ----------------------------------------------------
.SH RETURN VALUE
The \f[B]explain_lchmod_or_die\fP function only returns on success, see
\f[I]lchmod\fP(2) for more information. On failure, prints an explanation
and exits, it does not return.
.PP
The \f[B]explain_lchmod_on_error\fP function always returns the value
return by the wrapped \f[I]lchmod\fP(2) system call.
.\" ----------------------------------------------------
.SH EXAMPLE
The \f[B]explain_lchmod_or_die\fP function is intended to be used in a
fashion similar to the following example:
.RS
.ft CW
.nf
explain_lchmod_or_die(pathname, mode);
.fi
.ft R
.RE
.\" ----------------------------------------------------
.SH SEE ALSO
.TP 8n
\f[I]lchmod\fP(2)
change permissions of a file
.TP 8n
\f[I]explain_lchmod\fP(3)
explain \f[I]lchmod\fP(2) errors
.TP 8n
\f[I]exit\fP(2)
terminate the calling process
.\" ----------------------------------------------------
.SH COPYRIGHT
.so etc/version.so
.if n .ds C) (C)
.if t .ds C) \(co
libexplain version \*(v)
.br
Copyright \*(C) 2012 Peter Miller
.\" vim: set ts=8 sw=4 et :
