.\"
.\" libexplain - Explain errno values returned by libc functions
.\" Copyright (C) 2009-2011 Peter Miller
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or (at
.\" your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program. If not, see <http://www.gnu.org/licenses/>.
.\"
.ds n) explain_getpeername
.cp 0  \" Solaris defaults to ''.cp 1'', sheesh.
.TH explain_getpeername 3
.SH NAME
explain_getpeername \- explain getpeername(2) errors
.if require_index \{
.XX "explain_getpeername(3)" "explain getpeername(2) errors"
.\}
.SH SYNOPSIS
#include <libexplain/getpeername.h>
.sp 0.3
const char *explain_getpeername(int fildes, struct sockaddr *sock_addr,
socklen_t *sock_addr_size);
.br
const char *explain_errno_getpeername(int errnum, int fildes,
struct sockaddr *sock_addr, socklen_t *sock_addr_size);
.br
void explain_message_getpeername(char *message, int message_size,
int fildes, struct sockaddr *sock_addr, socklen_t *sock_addr_size);
.br
void explain_message_errno_getpeername(char *message, int message_size,
int errnum, int fildes, struct sockaddr *sock_addr, socklen_t *sock_addr_size);
.SH DESCRIPTION
These functions may be used to obtain explanations for
errors returned by the \f[I]getpeername\fP(2) system call.
.\" ----------------------------------------------------
.SS explain_getpeername
const char *explain_getpeername(int fildes, struct sockaddr *sock_addr,
socklen_t *sock_addr_size);
.PP
The \f[B]explain_getpeername\fP function is
used to obtain an explanation of an error returned by the \f[I]getpeername\fP(2)
system call.  The least the message will contain is the
value of \f[CW]strerror(errno)\fP, but usually it will
do much better, and indicate the underlying cause in more
detail.
.PP
The \f[I]errno\fP global variable will be used to obtain
the error value to be decoded.
.PP
This function is intended to be used in a fashion
similar to the following example:
.RS
.ft CW
.nf
struct sockaddr sock_addr;
socklen_t sock_addr_len = sizeof(sock_addr);
if (getpeername(fildes, &sock_addr, &sock_addr_size) < 0)
{
    fprintf(stderr, "%s\en", explain_getpeername(fildes,
        &sock_addr, &sock_addr_size));
    exit(EXIT_FAILURE);
}
.fi
.ft R
.RE
.PP
The above code example is available pre\[hy]packaged as the
\f[I]explain_getpeername_or_die\fP(3) function.
.TP 8n
\f[I]fildes\fP
The original fildes, exactly as passed to the \f[I]getpeername\fP(2)
system call.
.TP 8n
\f[I]sock_addr\fP
The original sock_addr, exactly as passed to the \f[I]getpeername\fP(2)
system call.
.TP 8n
\f[I]sock_addr_size\fP
The original sock_addr_size, exactly as passed to the
\f[I]getpeername\fP(2) system call.
.TP 8n
Returns:
The message explaining the error.  This message buffer is
shared by all libexplain functions which do not supply a
buffer in their argument list.  This will be overwritten
by the next call to any libexplain function which shares
this buffer, including other threads.
.PP
\f[B]Note:\fP
This function is \f[B]not\fP thread safe, because it
shares a return buffer across all threads, and many other
functions in this library.
.\" ----------------------------------------------------
.SS explain_errno_getpeername
const char *explain_errno_getpeername(int errnum, int fildes,
struct sockaddr *sock_addr, socklen_t *sock_addr_size);
.PP
The \f[B]explain_errno_getpeername\fP function
is used to obtain an explanation of an error returned by
the \f[I]getpeername\fP(2) system call.
The least the message will contain is the value of
\f[CW]strerror(errnum)\fP, but usually it will do much
better, and indicate the underlying cause in more detail.
.PP
This function is intended to be used in a fashion
similar to the following example:
.RS
.ft CW
.nf
struct sockaddr sock_addr;
socklen_t sock_addr_len = sizeof(sock_addr);
if (getpeername(fildes, &sock_addr, &sock_addr_size) < 0)
{
    int err = errno;
    fprintf(stderr, "%s\en", explain_errno_getpeername(err,
        fildes, &sock_addr, &sock_addr_size));
    exit(EXIT_FAILURE);
}
.fi
.ft R
.RE
.PP
The above code example is available pre\[hy]packaged as the
\f[I]explain_getpeername_or_die\fP(3) function.
.TP 8n
\f[I]errnum\fP
The error value to be decoded, usually obtained from
the \f[I]errno\fP global variable just before this
function is called.  This is necessary if you need to call
\f[B]any\fP code between the system call to be explained
and this function, because many libc functions will alter
the value of \f[I]errno\fP.
.TP 8n
\f[I]fildes\fP
The original fildes, exactly as passed to the \f[I]getpeername\fP(2)
system call.
.TP 8n
\f[I]sock_addr\fP
The original sock_addr, exactly as passed to the \f[I]getpeername\fP(2)
system call.
.TP 8n
\f[I]sock_addr_size\fP
The original sock_addr_size, exactly as passed to the
\f[I]getpeername\fP(2) system call.
.TP 8n
Returns:
The message explaining the error.  This message buffer is
shared by all libexplain functions which do not supply a
buffer in their argument list.  This will be overwritten
by the next call to any libexplain function which shares
this buffer, including other threads.
.PP
\f[B]Note:\fP
This function is \f[B]not\fP thread safe, because it
shares a return buffer across all threads, and many other
functions in this library.
.\" ----------------------------------------------------
.SS explain_message_getpeername
void explain_message_getpeername(char *message, int message_size,
int fildes, struct sockaddr *sock_addr, socklen_t *sock_addr_size);
.PP
The \f[B]explain_message_getpeername\fP
function may be used to  obtain an explanation of an error
returned by the
\f[I]getpeername\fP(2) system call.
The least the message will contain is the value of
\f[CW]strerror(errno)\fP, but usually it will do much
better, and indicate the underlying cause in more detail.
.PP
The \f[I]errno\fP global variable will be used to obtain
the error value to be decoded.
.PP
This function is intended to be used in a fashion
similar to the following example:
.RS
.ft CW
.nf
struct sockaddr sock_addr;
socklen_t sock_addr_len = sizeof(sock_addr);
if (getpeername(fildes, &sock_addr, &sock_addr_size) < 0)
{
    char message[3000];
    explain_message_getpeername(message, sizeof(message),
        fildes, &sock_addr, &sock_addr_size);
    fprintf(stderr, "%s\en", message);
    exit(EXIT_FAILURE);
}
.fi
.ft R
.RE
.PP
The above code example is available pre\[hy]packaged as the
\f[I]explain_getpeername_or_die\fP(3) function.
.TP 8n
\f[I]message\fP
The location in which to store the returned message.
If a suitable message return buffer is supplied, this
function is thread safe.
.TP 8n
\f[I]message_size\fP
The size in bytes of the location in which to
store the returned message.
.TP 8n
\f[I]fildes\fP
The original fildes, exactly as passed to the \f[I]getpeername\fP(2)
system call.
.TP 8n
\f[I]sock_addr\fP
The original sock_addr, exactly as passed to the \f[I]getpeername\fP(2)
system call.
.TP 8n
\f[I]sock_addr_size\fP
The original sock_addr_size, exactly as passed to the
\f[I]getpeername\fP(2) system call.
.\" ----------------------------------------------------
.SS explain_message_errno_getpeername
void explain_message_errno_getpeername(char *message, int message_size,
int errnum, int fildes, struct sockaddr *sock_addr, socklen_t *sock_addr_size);
.PP
The \f[B]explain_message_errno_getpeername\fP
function may be used to obtain an explanation of an error
returned by the
\f[I]getpeername\fP(2) system call.
The least the message will contain is the value of
\f[CW]strerror(errnum)\fP, but usually it will do much
better, and indicate the underlying cause in more detail.
.PP
This function is intended to be used in a fashion
similar to the following example:
.RS
.ft CW
.nf
struct sockaddr sock_addr;
socklen_t sock_addr_len = sizeof(sock_addr);
if (getpeername(fildes, &sock_addr, &sock_addr_size) < 0)
{
    int err = errno;
    char message[3000];
    explain_message_errno_getpeername(message, sizeof(message),
        err, fildes, &sock_addr, &sock_addr_size);
    fprintf(stderr, "%s\en", message);
    exit(EXIT_FAILURE);
}
.fi
.ft R
.RE
.PP
The above code example is available pre\[hy]packaged as the
\f[I]explain_getpeername_or_die\fP(3) function.
.TP 8n
\f[I]message\fP
The location in which to store the returned message.
If a suitable message return buffer is supplied, this
function is thread safe.
.TP 8n
\f[I]message_size\fP
The size in bytes of the location in which to
store the returned message.
.TP 8n
\f[I]errnum\fP
The error value to be decoded, usually obtained from
the \f[I]errno\fP global variable just before this
function is called.  This is necessary if you need to call
\f[B]any\fP code between the system call to be explained
and this function, because many libc functions will alter
the value of \f[I]errno\fP.
.TP 8n
\f[I]fildes\fP
The original fildes, exactly as passed to the \f[I]getpeername\fP(2)
system call.
.TP 8n
\f[I]sock_addr\fP
The original sock_addr, exactly as passed to the \f[I]getpeername\fP(2)
system call.
.TP 8n
\f[I]sock_addr_size\fP
The original sock_addr_size, exactly as passed to the
\f[I]getpeername\fP(2) system call.
.\" ----------------------------------------------------
.SH SEE ALSO
.TP 8n
\f[I]getpeername\fP(2)
get name of connected peer socket
.TP 8n
\f[I]explain_getpeername_or_die\fP(3)
get name of connected peer socket and report errors
.\" ----------------------------------------------------
.SH COPYRIGHT
.so etc/version.so
.if n .ds C) (C)
.if t .ds C) \(co
libexplain version \*(v)
.br
Copyright \*(C) 2009 Peter Miller
.\" vim: set ts=8 sw=4 et
